# -------------------------------------------------------------
# GitHub Pages Custom Domain (kcontents.site) 설정
# -------------------------------------------------------------
baseurl: ""                 # 커스텀 도메인 사용 시 반드시 "" (빈 문자열)으로 설정합니다.
url: "https://kcontents.site" # 블로그의 전체 주소를 HTTPS 포함하여 입력합니다.

# -------------------------------------------------------------
# Build settings (나머지 설정은 그대로 유지)
# -------------------------------------------------------------
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
