# -------------------------------
# General Site Settings
title: K-Contents Hub
logo: # site icon.png # 로고 파일이 있다면 경로를 입력하세요 
description: K-Contents Hub shares K-POP MV analysis, lyrics, and Korean culture in English for global fans.


#-------------------------------
# Author Settings
author:
  name: K-Contents Curator
  image: # 01.jpg # 이미지 파일 경로를 입력하세요 (현재는 비워둡니다).
  say-hello: Hello! I'm <strong>K-Contents Hub</strong>
  bio: Your go-to source for deep analysis of <strong>K-POP</strong> MVs, lyrics, and cultural insights. Join the global fan discussion!


#-------------------------------
# Contact links (팔로우/소셜 미디어 링크)


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # 여기에 Disqus Shortname을 입력하여 댓글 기능을 활성화하세요.


#-------------------------------
# Instagram Feed
instafeed: false # 인스타그램 피드를 사용하지 않을 경우 false로 설정합니다.
instagram-profile: # 인스타그램 피드를 사용하지 않으므로 비워둡니다.


#-------------------------------
# Google Analytics
google-analytics: # 여기에 Google Analytics 추적 ID (UA-XXXXX)를 입력하세요.


#-------------------------------
# Newsletter
mailchimp: # 뉴스레터 서비스를 사용하지 않으면 비워둡니다.
